import { IntegrationApp } from "./connect-types";

export const DEFAULT_INTEGRATIONS: IntegrationApp[] = [
  {
    id: "gmail",
    pluginName: "gmail",
    name: "Gmail",
    tagline: "Google Workspace & Personal Mail",
    description:
      "Read incoming threads, compose replies with AI assistance, manage Gmail labels, and organize your inbox effortlessly.",
    category: "email",
    categoryLabel: "Email & Mailbox",
    connected: false,
    capabilities: [
      "Two-way thread synchronization",
      "AI drafting & smart suggestions",
      "Label management & filters",
      "Real-time push notifications",
    ],
    permissions: ["https://mail.google.com/", "Read & send emails", "Manage labels"],
    accentColor: "#EA4335",
    bgAccent: "#FEF2F2",
    badge: "Primary",
    canRealConnect: true,
    connectEndpoint: "/api/integrations/gmail/connect",
    docsUrl: "https://support.google.com/mail",
  },
  {
    id: "calendar",
    pluginName: "googlecalendar",
    name: "Google Calendar",
    tagline: "Events, Scheduling & Time Blocking",
    description:
      "Sync your agenda, time-block tasks, preview day and week schedules, and join virtual meetings with one click.",
    category: "calendar",
    categoryLabel: "Calendar & Schedule",
    connected: false,
    capabilities: [
      "Real-time event sync (Week & Month views)",
      "Smart conflict detection",
      "Meeting join links & Google Meet integration",
      "Focus time blocks",
    ],
    permissions: ["calendar.events", "calendar.readonly", "Read & modify schedules"],
    accentColor: "#4285F4",
    bgAccent: "#EFF6FF",
    badge: "Primary",
    canRealConnect: true,
    connectEndpoint: "/api/integrations/calendar/connect",
    docsUrl: "https://calendar.google.com",
  },
  {
    id: "outlook",
    pluginName: "outlook",
    name: "Microsoft Outlook",
    tagline: "Microsoft 365 & Exchange Mail",
    description:
      "Connect your enterprise Microsoft 365 or personal Outlook account to unify corporate communications in one place.",
    category: "email",
    categoryLabel: "Email & Mailbox",
    connected: false,
    capabilities: [
      "Exchange & Microsoft 365 mailbox sync",
      "Outlook calendar events & invites",
      "Shared folder hierarchy",
      "Enterprise single sign-on",
    ],
    permissions: ["Mail.ReadWrite", "Calendars.ReadWrite", "User.Read", "offline_access"],
    accentColor: "#0078D4",
    bgAccent: "#EFF6FF",
    badge: "Enterprise",
    canRealConnect: false,
    docsUrl: "https://learn.microsoft.com/en-us/graph/outlook-concept-overview",
  },
  {
    id: "slack",
    pluginName: "slack",
    name: "Slack",
    tagline: "Team Messaging & Channel Alerts",
    description:
      "Receive channel pings, turn important thread discussions into tasks, and reply directly from Command Inbox.",
    category: "communication",
    categoryLabel: "Team Collaboration",
    connected: false,
    capabilities: [
      "Channel message digest & mentions",
      "Direct message sync",
      "Convert message threads to email tasks",
      "Quick emoji reactions & status sync",
    ],
    permissions: ["channels:read", "chat:write", "users:read", "team:read"],
    accentColor: "#4A154B",
    bgAccent: "#FAF5FF",
    badge: "Popular",
    canRealConnect: false,
    docsUrl: "https://api.slack.com",
  },
  {
    id: "notion",
    pluginName: "notion",
    name: "Notion",
    tagline: "Docs, Wikis & Database Tasks",
    description:
      "Capture action items from emails straight into your Notion databases, link meeting notes, and sync project cards.",
    category: "productivity",
    categoryLabel: "Productivity & Docs",
    connected: false,
    capabilities: [
      "Export email summaries to database pages",
      "Two-way task status tracking",
      "Attach meeting agendas to calendar events",
      "Workspace search preview",
    ],
    permissions: ["Read content", "Update content", "Insert pages to databases"],
    accentColor: "#18181B",
    bgAccent: "#F4F4F5",
    badge: "Productivity",
    canRealConnect: false,
    docsUrl: "https://developers.notion.com",
  },
  {
    id: "zoom",
    pluginName: "zoom",
    name: "Zoom",
    tagline: "Video Meetings & Call Summaries",
    description:
      "Generate instant meeting links for calendar invites, record transcriptions, and summarize discussions with AI.",
    category: "communication",
    categoryLabel: "Team Collaboration",
    connected: false,
    capabilities: [
      "One-click video call generation",
      "Attach meeting links to events",
      "Automatic recording & transcription digest",
    ],
    permissions: ["meeting:write", "meeting:read", "user:read"],
    accentColor: "#2D8CFF",
    bgAccent: "#EFF6FF",
    canRealConnect: false,
    docsUrl: "https://marketplace.zoom.us/docs/api-reference",
  },
  {
    id: "linear",
    pluginName: "linear",
    name: "Linear",
    tagline: "Issue Tracking & Sprint Planning",
    description:
      "Turn customer emails, bug reports, and product feedback directly into Linear issues linked to your active cycle.",
    category: "productivity",
    categoryLabel: "Productivity & Docs",
    connected: false,
    capabilities: [
      "Create Linear issues from email threads",
      "Assign issues & set team priorities",
      "Link customer replies to existing tickets",
    ],
    permissions: ["issues:create", "read", "write"],
    accentColor: "#5E6AD2",
    bgAccent: "#EEF0FB",
    badge: "Developer",
    canRealConnect: false,
    docsUrl: "https://linear.app/docs",
  },
  {
    id: "github",
    pluginName: "github",
    name: "GitHub",
    tagline: "Code Reviews, Pull Requests & Issues",
    description:
      "Keep track of review requests, CI failure notifications, and repository discussions without leaving your inbox.",
    category: "productivity",
    categoryLabel: "Developer Tools",
    connected: false,
    capabilities: [
      "Pull request review alerts",
      "Issue thread mentions & assignments",
      "GitHub Actions build status preview",
    ],
    permissions: ["repo", "notifications", "read:user"],
    accentColor: "#24292F",
    bgAccent: "#F3F4F6",
    canRealConnect: false,
    docsUrl: "https://docs.github.com",
  },
];
